hyperparameters:
  learning_rate: 0.1
  iterations: 50
  max_depth: 4
  l2_leaf_reg: 2
  subsample:  0.8
  random_state: 22
  loss_function: MAE

directories:
  model_dir: dvc/model
  output_dir: dvc/output
  output_data_dir: dvc/output/data
  output_intermediate_dir: dvc/output/intermediate

datasets:
  train: data/train
  train_file: train.csv
  test: data/test
  test_file: test.csv
  y_column: yield
  drop_columns:
    - global_trend
    - V0_temperature_c_surface_avg
    - V0_temperature_c_surface_max
    - V0_temperature_c_surface_min
    - V0_mean_cvi
    - V0_std_cvi
    - V0_median_cvi
    - V0_q10_cvi
    - V0_q25_cvi
    - V0_q75_cvi
    - V0_q90_cvi
    - V0_mean_cab
    - V0_std_cab
    - V0_median_cab
    - V0_q10_cab
    - V0_q25_cab
    - V0_q75_cab
    - V0_q90_cab
    - V0_mean_ecnorm
    - V0_std_ecnorm
    - V0_median_ecnorm
    - V0_q10_ecnorm
    - V0_q25_ecnorm
    - V0_q75_ecnorm
    - V0_q90_ecnorm
    - V0_mean_evi2
    - V0_std_evi2
    - V0_median_evi2
    - V0_q10_evi2
    - V0_q25_evi2
    - V0_q75_evi2
    - V0_q90_evi2
    - V0_mean_gndvi
    - V0_std_gndvi
    - V0_median_gndvi
    - V0_q10_gndvi
    - V0_q25_gndvi
    - V0_q75_gndvi
    - V0_q90_gndvi
    - V0_mean_gvmi
    - V0_std_gvmi
    - V0_median_gvmi
    - V0_q10_gvmi
    - V0_q25_gvmi
    - V0_q75_gvmi
    - V0_q90_gvmi
    - V0_mean_lai
    - V0_std_lai
    - V0_median_lai
    - V0_q10_lai
    - V0_q25_lai
    - V0_q75_lai
    - V0_q90_lai
    - V0_mean_mcari
    - V0_std_mcari
    - V0_median_mcari
    - V0_q10_mcari
    - V0_q25_mcari
    - V0_q75_mcari
    - V0_q90_mcari
    - V0_mean_msavi
    - V0_std_msavi
    - V0_median_msavi
    - V0_q10_msavi
    - V0_q25_msavi
    - V0_q75_msavi
    - V0_q90_msavi
    - V0_mean_nddi
    - V0_std_nddi
    - V0_median_nddi
    - V0_q10_nddi
    - V0_q25_nddi
    - V0_q75_nddi
    - V0_q90_nddi
    - V0_mean_ndvi
    - V0_std_ndvi
    - V0_median_ndvi
    - V0_q10_ndvi
    - V0_q25_ndvi
    - V0_q75_ndvi
    - V0_q90_ndvi
    - V0_mean_ndwi
    - V0_std_ndwi
    - V0_median_ndwi
    - V0_q10_ndwi
    - V0_q25_ndwi
    - V0_q75_ndwi
    - V0_q90_ndwi
    - V0_mean_pvi
    - V0_std_pvi
    - V0_median_pvi
    - V0_q10_pvi
    - V0_q25_pvi
    - V0_q75_pvi
    - V0_q90_pvi
    - V0_mean_slavi
    - V0_std_slavi
    - V0_median_slavi
    - V0_q10_slavi
    - V0_q25_slavi
    - V0_q75_slavi
    - V0_q90_slavi
    - V0_mean_vsdi
    - V0_std_vsdi
    - V0_median_vsdi
    - V0_q10_vsdi
    - V0_q25_vsdi
    - V0_q75_vsdi
    - V0_q90_vsdi
    - V0_mean_wet
    - V0_std_wet
    - V0_median_wet
    - V0_q10_wet
    - V0_q25_wet
    - V0_q75_wet
    - V0_q90_wet
    - V0_mean_fapar
    - V0_std_fapar
    - V0_median_fapar
    - V0_q10_fapar
    - V0_q25_fapar
    - V0_q75_fapar
    - V0_q90_fapar